is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind -n C-h if-shell "$is_vim" "send-keys C-h"  "select-pane -L"
bind -n C-j if-shell "$is_vim" "send-keys C-j"  "select-pane -D"
bind -n C-k if-shell "$is_vim" "send-keys C-k"  "select-pane -U"
bind -n C-l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"
bind -n C-\\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"

bind -r Left  resize-pane -L 5
bind -r Down  resize-pane -D 5
bind -r Up    resize-pane -U 5
bind -r Right resize-pane -R 5

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

set-option -g default-terminal tmux-256color
set -as terminal-features ",tmux-256color:RGB"

set -g base-index 1
set -g pane-base-index 1

set -g mouse on
set-option -g status "on"
set -g 'status-format[1]' ''
set -g status 2

set-option -g status-position top

set -g message-style fg='#faf4ed',bg='#b4637a',bold

set-option -g pane-border-style fg='#cecacd'
set-option -g pane-active-border-style fg='#56949f'

set-option -g status-fg '#e0def4'
set-option -g status-bg 'default'

set-option -g mode-style fg='#faf4ed',bg='#286983'

set-window-option -g clock-mode-colour '#907aa9'

set-option -g status-style fg='#e0def4',bg='default'

set-window-option -g window-status-style fg='#c4c0d9',bg='default'

set-window-option -g window-status-activity-style bg='default',fg='#c4c0d9'
set-window-option -g window-status-current-style fg='#faf4ed',bg='#286983'

set-option -g status-left-style none
set -g status-left-length 60
set -g status-left ''

set-option -g status-right-style none
set -g status-right-length 120
set -g status-right '#[fg=#b4637a]#[fg=#faf4ed,bg=#b4637a]  #[fg=#575279,bg=#f2e9e1] #W #[fg=#56949f]#[fg=#faf4ed,bg=#56949f]  #[fg=#575279,bg=#f2e9e1] #{pane_current_path} #[fg=#286983]#[fg=#faf4ed,bg=#286983]  #[fg=#575279,bg=#f2e9e1] #S '

set -g window-status-separator "#[bg=default] "
set -g window-status-current-format "#[fg=#575279,bg=#f2e9e1] #W #[fg=#f2e9e1,bg=#286983] #I#[fg=#286983,bg=default]"
set -g window-status-format "#[fg=#575279,bg=#f2e9e1] #W #[fg=#f2e9e1,bg=#907aa9] #I#[fg=#907aa9,bg=default]"

set -g @plugin 'tmux-plugins/tpm'
run '~/.config/tmux/plugins/tpm/tpm'
